### ISSUE TITLE
JSON syntax error in the user commands configuration?

### ISSUE THREAD

**Issue by cyberbu11y** [NuclearCoder/nuclear-bot#6]
`[2016-09-8 04:26:00] ERROR: (GUI) JSON syntax error while loading user commands:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
    at com.google.gson.Gson.fromJson(Gson.java:899)
    at com.google.gson.Gson.fromJson(Gson.java:852)
    at com.google.gson.Gson.fromJson(Gson.java:801)
    at com.google.gson.Gson.fromJson(Gson.java:773)
    at nuclearbot.gui.ControlPanel.loadUserCommands(ControlPanel.java:644)
    at nuclearbot.gui.ControlPanel.<init>(ControlPanel.java:553)
    at nuclearbot.Main.run(Main.java:61)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
    at com.google.gson.Gson.fromJson(Gson.java:887)
    ... 20 more`

**Comment by cyberbu11y** [comment]
This is the error message in the console.

**Comment by NuclearCoder** [comment]
Edit the config.properties file and set user_commands to {}

**Comment by NuclearCoder** [comment]
Or rather, show me what is the current value

**Comment by cyberbu11y** [comment]
I used the release, this message appears when I open the program right after downloading.

config.properties:

`twitch_user=your Twitch username
twitch_oauth_key=your Twitch oauth token 
last_plugin=
user_commands={}`

**Comment by NuclearCoder** [comment]
And is it still not working after changing to {} ?
IIRC it shouldn't prevent you from using the bot, only from creating custom commands

**Comment by cyberbu11y** [comment]
No, it doesn't work (the config.properties came like that). I don't think any of the other stuff is working either. 

I use a mac if it has anything to do with it

**Comment by NuclearCoder** [comment]
By the way, it can't work if you haven't put your Twitch stuff in the file. Check wiki for how to configure

**Comment by cyberbu11y** [comment]
Oh, did not know that. 

Unrelated question: how do you get your oauth token?

**Comment by NuclearCoder** [comment]
Be careful with the !np command for osu, I don't have any Mac OS computer around so it doesn't support it. If you agree to help me support Macs, I'd be delighted :3

**Comment by cyberbu11y** [comment]
Sure! I'd be happy to. would be even better if I got some java experience as well

**Comment by cyberbu11y** [comment]
After configuring Nuclearbot, it still gives the same error, even with my token and username inputted and user_commands={}.

**Comment by NuclearCoder** [comment]
it's still that? Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2

**Comment by NuclearCoder** [comment]
weird...

**Comment by NuclearCoder** [comment]
Aye, I'll build a release, I finally came back to the project and cleaned all this mess up :'3
